### ISSUE TITLE
Import account by moving funds Hangs

### ISSUE THREAD

**Issue by snub-fighter** [casinocoin/casinocoin-token-wallet#17] opened 2020-03-01 04:22 UTC
When attempting to import an external account with the import-only toggle disabled (grey) the OK button shows a spinner but no progress is made.  Nothing happens.  Import-Only with toggle enabled (blue) does work.

I left it for about 10 mins and no change.  No errors, just spins.

Wallet Ver : 5.0.8
OS: Win 10 x64

**Comment by Alexb7575** [comment] 2020-03-02 00:55
On Mac (Mojave 10.14.6) withWallet 5.0.8, I have the same problem, even with Import Only with toggle enabled.

**Comment by t3nshi** [comment] 2020-03-02 19:45
The import only means that you are including the key and will handle it from wallet without adding the account to the seed. It won't be recoverable by the seed of 12 words (but if you have a the secret you can recover the accout anyway, just don't lose or give away that secret.) . But if you want to be able to recover it from seed words you need to create the key and secret inside that wallet, that's way there is another option that move all funds to your wallet.  
So you tried to import with toggle disabled ( so you moved the funds), the process didn't seem to progress and you left it a lot of time. (You had connection all that time to the  production network right?) and then tried to import again (but the funds where moved already, aren't they? so the account may be empty) and it worked? I'm not sure if I'm understanding correctly here.

**Comment by snub-fighter** [comment] 2020-03-02 19:49
Thanks @t3nshi for responding.  Yes I successfully tested the "import only" feature.  I was testing import with the "import only" disabled.
1. Yes network connection was available the entire time.
2. There were funds in the other account and nothing was moved.  Cancelling the action (clicking on X) only brought me back to wallet.  No changes, nothing imported. 

In short having import only disabled and entering in secret + wallet passphrase then clicking OK did nothing.

**Comment by t3nshi** [comment] 2020-03-02 19:50
so the funds where not moved then?

**Comment by snub-fighter** [comment] 2020-03-02 19:51
No funds were moved.

**Comment by t3nshi** [comment] 2020-03-02 19:54
let me check and I will get back to you later.

**Comment by t3nshi** [comment] 2020-03-02 20:37
I just tried a couple of times. In my case the key is imported by moving the funds. And I don't get stuck on anything. Can you please recheck that you are providing the complete information and that you are not missing any step so your problem can be reproduced?

**Comment by Alexb7575** [comment] 2020-03-02 21:02
Still the same problem.
I have made a screen capture, it s here : https://we.tl/t-0z7tse2J8C
(I used an old secret from an account I am not using)

**Comment by t3nshi** [comment] 2020-03-02 21:28
thanks for letting us know that you still have a problem. I do not know what you expect to show me on that video. An account you are not using means that it is empty? because I just tested what the OP asked and that was importing a key by moving funds. That cannot be done with an empty account (obviously) so, if you have an entirely different problem, please try to put all the information in a new issue. Make sure that you tested it beforehand so you can provide all steps and relevant information. If your problem is similar or the same to the one presented here, make sure to provide all the useful information so we can replicate it, it might help more than a video to know full details. If for example the account you tried was not even activated ever... that is much more relevant that what you showed on the video. Or if for example there is an account that have, say 15k of transactions... thanks a lot for taking the time to test and report all problems and we will try to help you once we know more about your problem. @Alexb7575

**Comment by Alexb7575** [comment] 2020-03-02 21:46
Thank you for your time.

The secret is from an account that is activated. It is this one :
https://csc.observer/account/chZP6DwYamTfYqEAmR6CbvLvPn1i6SPvkR

It is not exactly the same problem as OP, but it is the same consequence (ok button keeps spinning)

I have just set up my CRN and would like to add it to my desktop wallet (as it is not possible to add it to the mobile wallet). I want to check that everything is ok (see if I can withdraw or fund from it). 

I have activated the CRN account (with the activate! command on discord, so it has 10 csc). But, whenever I try to add the CRN account to the wallet, I have what happens in the video : Import private key / Secret + password / enable "import only" > Then the Ok button keeps spinning....

**Comment by t3nshi** [comment] 2020-03-02 22:30
thanks for providing additional information on this. It's helpful to have some context. What do you mean is not possible on the mobile wallet. Which mobile wallet are you using. Other thing is, can you try this with a different account to validate that this not something account specific, and that your issue will happen no matter the account. For instance, with an account on the mobile wallet.

**Comment by Alexb7575** [comment] 2020-03-02 22:44
I use Mobile iOS  ver 4.1.2
I think I read Daniel told not to add the CRN account on mobile wallet.

I have tried with an account from my mobile wallet, same problem.

**Comment by snub-fighter** [comment] 2020-03-05 18:33
@t3nshi Is it possible this is an issue with testnet and not prod?  I made a new primary wallet on a new machine (Main) to see if it was the wallet/pc.  

I have been testing on two different machines and both fail when importing.
As these are testnet accounts im not concerned about secret keys, unless you are.  So you can try them out if desired.

#### Main  
caeB7TzRXpAUtUTMik4kQBfkpTWPMbeMTs  
#### To Import  
ssUi8cJJdt1vhGXW59PLmCW62BPrC  

![image](https://user-images.githubusercontent.com/5192578/76013194-6770b380-5ecc-11ea-925d-29bfad6448c5.png)

**Comment by t3nshi** [comment] 2020-03-05 22:02
Will do and let you know later. Thanks!

**Comment by viktorhugo** [comment] 2020-05-14 22:02
fixed in version 5.0.9

**Closed as completed by viktorhugo** 2020-05-14 22:02 UTC
Labels: bug, question
